//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 
namespace JRC.IPSC.MARS.Utilities {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ParametersComponentDescriptionsConfig {
        
        private ParametersComponentDescriptionsConfigComponentDescription[] componentDescriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ComponentDescription")]
        public ParametersComponentDescriptionsConfigComponentDescription[] ComponentDescription {
            get {
                return this.componentDescriptionField;
            }
            set {
                this.componentDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ParametersComponentDescriptionsConfigComponentDescription {
        
        private string componentDescriptorTypeField;
        
        private string parameterEditorTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ComponentDescriptorType {
            get {
                return this.componentDescriptorTypeField;
            }
            set {
                this.componentDescriptorTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ParameterEditorType {
            get {
                return this.parameterEditorTypeField;
            }
            set {
                this.parameterEditorTypeField = value;
            }
        }
    }
}
