# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources: 
    repositories:
      - repository: templates
        type: git
        name: BioMA.AzurePipelines/BioMA.AzurePipelines
        

trigger:
- master

pool:
  vmImage: 'windows-latest'

# these variables are available throughout the build  file
# just the build configuration is defined, in this case we are building Release packages
variables:
  BuildConfiguration: 'debug'
  MajorVersionOfArtifact: '3.0.0' # This must be incremented even when we prepare a new preliminary version,
                                  # starting from the decremented stable version
  SolutionPath: 'BioMA.Utilities\BioMA.Utilities\BioMA.Utilities.sln'

steps:
  - checkout: self
  - checkout: templates
  - template: templates/build.yml@templates